# Generated by Django 2.1.1 on 2018-09-16 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180916_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='answer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='liked_answer', to='core.Answer'),
        ),
    ]
