# Generated by Django 2.1.1 on 2018-09-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('N', 'Not Chosen'), ('M', 'Male'), ('F', 'Female')], default='N', max_length=2),
        ),
    ]
