# Generated by Django 2.1.1 on 2018-09-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
